#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 22 17:41:10 2022

@author: victor
"""

first_name = 'Albert'
last_name = 'Einstein'
full_name = first_name + ' ' + last_name
print(full_name)